name: Deploy Blog

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 拉取代码
    - name: Checkout code
      uses: actions/checkout@v4

    # ==========================================
    # 前端处理部分
    # ==========================================
    - name: Setup Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10 # 指定 pnpm 版本 10+

    - name: Install Frontend Dependencies
      run: |
        pnpm install

    - name: Build Frontend
      run: |
        pnpm run build
      # 如果你的前端在编译时需要读取环境变量 (如 VITE_API_URL)，请在此处传入:
      # env:
      #   VITE_API_URL: ${{ secrets.VITE_API_URL }}

    # ==========================================
    # 前端部署 (先删后传)
    # ==========================================
    - name: Deploy Frontend Dist
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # 定义目标路径
          DIST_PATH="/www/wwwroot/www.zhiniuyan.xyz/dist"
          
          # 如果 dist 目录存在，递归强制删除
          if [ -d "$DIST_PATH" ]; then
          echo "目录存在，正在清理旧文件（保留配置文件）..."
            cd $DIST_PATH
            find . -maxdepth 1 ! -name "." ! -name ".user.ini" -exec rm -rf {} \;
          fi

    - name: Upload Frontend Dist
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "dist" # 本地打包后的路径
        target: "/www/wwwroot/www.zhiniuyan.xyz/dist" # 服务器父目录
        strip_components: 1 # 去掉路径层级